name: Feature Request
description: Suggest a new feature or module
title: "[Feature]: "
labels: ["enhancement"]
body:
  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: What problem does this feature solve?
    validations:
      required: true
  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: How should this be implemented?
    validations:
      required: true
  - type: dropdown
    id: phase
    attributes:
      label: ATT&CK Phase
      description: Which phase of the kill chain does this relate to?
      options:
        - Reconnaissance
        - Resource Development
        - Initial Access
        - Execution
        - Persistence
        - Privilege Escalation
        - Defense Evasion
        - Credential Access
        - Discovery
        - Lateral Movement
        - Collection
        - Exfiltration
        - Command and Control
        - Impact
        - LLM/AI Security
        - Reporting/Orchestration
        - Other
    validations:
      required: true
